spring:
  datasource:
    url: jdbc:mysql://localhost:3306/finance?serverTimezone=Asia/Seoul
    username: root
    password: Abcd123@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

  security:
    filter:
      dispatcher-types:

  mvc:
    hiddenmethod:
      filter:
        enabled=true: true
logging:
  level:
    org.hibernate.SQL: debug
